openapi: 3.0.0
info:
  title: Core
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /accounts2:
    get:
      summary: List accounts
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/policy.v1.yaml
    parameters: []
components:
  schemas: {}
